### ISSUE TITLE
binder issue

### ISSUE THREAD

**Issue by koaning** [ines/course-starter-python#1]
love the idea. 

it seems something is up with binder though. 

![image](https://user-images.githubusercontent.com/1019791/56426982-810c0b00-62ba-11e9-8148-771c8de5b6e3.png)

figured it'd mention it so that you're aware of it.

**Comment by sammous** [comment]
you need to replace _ _ _ _ with the actual values

![image](https://user-images.githubusercontent.com/7331072/56452814-5200a280-6369-11e9-887b-eae3d1758fea.png)

**Comment by ines** [comment]
Yes – sorry if that was unclear. I didn't really question it, because it was just the default style in my course materials.

If you end up building your own course and you think it's confusing, it might make sense to add some instructions to the first exercises. Or maybe you want to use a different style for this (can't think of something right now, but maybe you have an idea).

The code area is powered by CodeMirror, so I was also thinking about potentially writing a plugin (?) or something that specifically highlights `____` to make it more obvious that those are the gaps.

**Comment by koaning** [comment]
ample explanation, thanks :)
